name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Specify the .NET version you want to use

    - name: Restore NuGet packages
      run: dotnet restore ImageProcessingTool/ImageProcessingTool.csproj  # Adjust path if necessary

    - name: Build solution
      run: dotnet build ImageProcessingTool/ImageProcessingTool.csproj --configuration Release  # Build the project

    - name: List files in Release directory
      run: dir "${{ github.workspace }}/ImageProcessingTool/bin/Release/net8.0-windows"

    - name: Publish the application
      run: dotnet publish ImageProcessingTool/ImageProcessingTool.csproj --configuration Release --output "${{ github.workspace }}/ImageProcessingTool/bin/Release/net8.0-windows"  # Publish the application

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ImageProcessingTool
        path: "${{ github.workspace }}/ImageProcessingTool/bin/Release/net8.0-windows"
          
  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: ImageProcessingTool

    - name: List files in downloaded artifact
      run: dir "${{ github.workspace }}/ImageProcessingTool/bin/Release/net8.0-windows" 

    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'v1.0.${{ github.run_number }}'
        release_name: 'Rangined - Image_Processing_Tool v1.0.${{ github.run_number }}'
        draft: false
        prerelease: false

    - name: Upload build to Release
      uses: svenstaro/upload-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "${{ github.workspace }}/ImageProcessingTool/bin/Release/net8.0-windows/ImageProcessingTool.exe"
        asset_name: ImageProcessingTool.exe
        tag: 'v1.0.${{ github.run_number }}'
